- console/package-lock.json
- pom.xml
- web/bin/shutdown.sh
- web/bin/startup.sh
- web/conf/application.yml
- web/pom.xml
- web/src/main/resources/assembly.xml
- run `mvn install ` to assembly kafka-manager-${project.version}.tar.gz 
- add `startup.sh` and `shutdown.sh`
- update fastjson's version to 1.2.68 for [security](https://github.com/alibaba/fastjson/releases)
> Add assembly and operation scripts to simplify deployment

- web/src/main/java/com/xiaojukeji/kafka/manager/web/api/versionone/OrderController.java
fix retention.ms when execute topic order
> fix retention.ms when execute topic order

- service/src/main/java/com/xiaojukeji/kafka/manager/service/service/OrderService.java
- service/src/main/java/com/xiaojukeji/kafka/manager/service/service/impl/JmxServiceImpl.java
- service/src/main/java/com/xiaojukeji/kafka/manager/service/service/impl/OrderServiceImpl.java
- web/src/main/java/com/xiaojukeji/kafka/manager/web/api/versionone/OrderController.java
> fix execute order partition

- kafka-manager-common/src/main/java/com/xiaojukeji/kafka/manager/common/utils/HttpUtils.java
- kafka-manager-console/src/container/admin/cluster-list/index.tsx
- kafka-manager-console/src/container/admin/config.tsx
- kafka-manager-console/src/container/admin/operation-management/config.tsx
- kafka-manager-console/src/container/admin/operation-management/migration-detail.tsx
- kafka-manager-console/src/container/alarm/add-alarm/alarm-select.tsx
- kafka-manager-console/src/container/alarm/add-alarm/config.tsx
- kafka-manager-console/src/container/alarm/add-alarm/index.tsx
- kafka-manager-console/src/container/alarm/alarm-detail/shield-history.tsx
- kafka-manager-console/src/container/alarm/alarm-list.tsx
- kafka-manager-console/src/container/app/app-list.tsx
- kafka-manager-console/src/container/modal/admin/cluster.ts
- kafka-manager-console/src/container/modal/admin/migration.ts
- kafka-manager-console/src/container/modal/admin/user.ts
- kafka-manager-console/src/container/modal/admin/version.ts
- kafka-manager-console/src/container/modal/alarm.tsx
- kafka-manager-console/src/container/modal/app.tsx
- kafka-manager-core/pom.xml
- kafka-manager-dao/pom.xml
- kafka-manager-extends/kafka-manager-account/pom.xml
- kafka-manager-extends/kafka-manager-bpm/pom.xml
- kafka-manager-extends/kafka-manager-kcm/pom.xml
- kafka-manager-extends/kafka-manager-monitor/pom.xml
- kafka-manager-extends/kafka-manager-openapi/pom.xml
- kafka-manager-task/pom.xml
- kafka-manager-web/pom.xml
- kafka-manager-web/src/main/java/com/xiaojukeji/kafka/manager/web/api/versionone/gateway/GatewayServiceDiscoveryController.java
- kafka-manager-web/src/main/java/com/xiaojukeji/kafka/manager/web/api/versionone/thirdpart/ThirdPartConsumeController.java
- pom.xml
> 文案优化|服务发现接口修复

- kafka-manager-task/src/main/java/com/xiaojukeji/kafka/manager/task/dispatch/metrics/store/SinkCommunityTopicMetrics2Monitor.java
- kafka-manager-task/src/main/java/com/xiaojukeji/kafka/manager/task/listener/SinkConsumerMetrics2Monitor.java
- kafka-manager-task/src/main/java/com/xiaojukeji/kafka/manager/task/listener/SinkTopicThrottledMetrics2Monitor.java
- kafka-manager-web/src/main/resources/application.yml
> 增加上报监控指标开关

- kafka-manager-web/src/main/java/com/xiaojukeji/kafka/manager/web/api/versionone/normal/NormalTopicController.java
- kafka-manager-web/src/main/java/com/xiaojukeji/kafka/manager/web/converters/TopicModelConverter.java
修复Topic详情中服务地址不展示问题。
Fix  https://github.com/didi/kafka-manager/issues/65
> 修复Topic详情中服务地址不展示问题

- .gitignore
- build.sh
> 增加build.sh

- kafka-manager-extends/kafka-manager-monitor/pom.xml
- kafka-manager-extends/kafka-manager-monitor/src/main/java/com/xiaojukeji/kafka/manager/monitor/component/n9e/N9eConverter.java
- kafka-manager-extends/kafka-manager-monitor/src/main/java/com/xiaojukeji/kafka/manager/monitor/component/n9e/N9eService.java
- kafka-manager-extends/kafka-manager-monitor/src/main/java/com/xiaojukeji/kafka/manager/monitor/component/n9e/entry/N9eStrategy.java
- kafka-manager-extends/kafka-manager-monitor/src/main/java/com/xiaojukeji/kafka/manager/monitor/component/n9e/entry/N9eStrategyAlertUpgrade.java
- kafka-manager-web/src/main/resources/application.yml
> FIX N9e Mon

- docs/dev_guide/Intergration_n9e_monitor.md
> 夜莺Mon集成配置说明

- docs/dev_guide/use_mysql_8.md
- docs/user_guide/faq.md
use mysql 8 
fix https://github.com/didi/Logi-KafkaManager/issues/100
> use mysql 8

- build.sh
- docs/install_guide/config_description.md
- docs/install_guide/install_guide_cn.md
- kafka-manager-common/pom.xml
- kafka-manager-console/pom.xml
- kafka-manager-core/pom.xml
- kafka-manager-dao/pom.xml
- kafka-manager-extends/kafka-manager-account/pom.xml
- kafka-manager-extends/kafka-manager-bpm/pom.xml
- kafka-manager-extends/kafka-manager-kcm/pom.xml
- kafka-manager-extends/kafka-manager-monitor/pom.xml
- kafka-manager-extends/kafka-manager-notify/pom.xml
- kafka-manager-extends/kafka-manager-openapi/pom.xml
- kafka-manager-task/pom.xml
- kafka-manager-web/pom.xml
- kafka-manager-web/src/main/resources/application.yml
- pom.xml
fix https://github.com/didi/Logi-KafkaManager/issues/107
>  增加application.yml文件说明 & 修改版本

- kafka-manager-common/src/main/java/com/xiaojukeji/kafka/manager/common/entity/ResultStatus.java
- kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/service/impl/ClusterServiceImpl.java
- kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/service/impl/ZookeeperServiceImpl.java
- kafka-manager-extends/kafka-manager-bpm/src/main/java/com/xiaojukeji/kafka/manager/bpm/order/impl/ApplyAuthorityOrder.java
- kafka-manager-extends/kafka-manager-kcm/src/main/java/com/xiaojukeji/kafka/manager/kcm/component/storage/local/Local.java
- kafka-manager-extends/kafka-manager-kcm/src/main/java/com/xiaojukeji/kafka/manager/kcm/impl/KafkaFileServiceImpl.java
> optimize result code

- kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/service/impl/TopicManagerServiceImpl.java
关联Issue：https://github.com/didi/Logi-KafkaManager/issues/160
将`__consumer_offsets`在全部Topic列表页隐藏
> Issue#160: Remove __consumer_offsets from topic list

- kafka-manager-common/pom.xml
- kafka-manager-common/src/test/java/com/xiaojukeji/kafka/manager/common/utils/JsonUtilsTest.java
- kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/service/impl/TopicManagerServiceImpl.java
[issue-153: [后端]操作记录检查&补充](https://github.com/didi/Logi-KafkaManager/issues/153)
已有的记录Topic增删改操作:
- 增：https://github.com/didi/Logi-KafkaManager/blob/44b7dd1808ce35c6f8b43be562de816466a5a89e/kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/service/impl/AdminServiceImpl.java#L87
- 删：https://github.com/didi/Logi-KafkaManager/blob/44b7dd1808ce35c6f8b43be562de816466a5a89e/kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/service/impl/AdminServiceImpl.java#L129
> Record topic operation

- kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/service/gateway/AppService.java
- kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/service/gateway/impl/AppServiceImpl.java
- kafka-manager-extends/kafka-manager-bpm/src/main/java/com/xiaojukeji/kafka/manager/bpm/order/impl/ApplyAppOrder.java
[issue-153: [后端]操作记录检查&补充](https://github.com/didi/Logi-KafkaManager/issues/153)
记录App的增删改操作。
已有功能：记录删除操作https://github.com/didi/Logi-KafkaManager/blob/ab0d1d99e66381f7f985c643f326fb2c1304f857/kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/service/gateway/impl/AppServiceImpl.java#L103
> Tracking changes applied to app

- kafka-manager-extends/kafka-manager-account/src/main/java/com/xiaojukeji/kafka/manager/account/AccountService.java
- kafka-manager-extends/kafka-manager-account/src/main/java/com/xiaojukeji/kafka/manager/account/impl/AccountServiceImpl.java
- kafka-manager-web/src/main/java/com/xiaojukeji/kafka/manager/web/api/versionone/rd/RdAccountController.java
[issue-153 [后端]操作记录检查&补充](https://github.com/didi/Logi-KafkaManager/issues/153)
记录删除账号操作。
> Tracking delete account

- kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/service/impl/ClusterServiceImpl.java
Fix：https://github.com/didi/Logi-KafkaManager/issues/148
> reject illegal zk address

- kafka-manager-task/src/main/java/com/xiaojukeji/kafka/manager/task/dispatch/op/SyncTopic2DB.java
bug fix: unexpected stop of the topic sync task
> bug fix: unexpected stop of the topic sync task

- kafka-manager-extends/kafka-manager-account/src/main/java/com/xiaojukeji/kafka/manager/account/component/sso/BaseSessionSignOn.java
bug fix:correct way to judge a user does not exist
> bug fix:correct way to judge a user does not exist

- kafka-manager-extends/kafka-manager-account/src/main/java/com/xiaojukeji/kafka/manager/account/impl/LoginServiceImpl.java
reject req when uri contains ..
> reject req when uri contains ..

- docs/user_guide/faq.md
add faq, kafka version supported & apply logical cluster and how to handle it
> add faq, kafka version supported & apply logical cluster and how to handle it

- kafka-manager-extends/kafka-manager-monitor/src/main/java/com/xiaojukeji/kafka/manager/monitor/component/n9e/N9eConverter.java
fix https://github.com/didi/Logi-KafkaManager/issues/206
> fix monitor enable time illegal bug

- docs/dev_guide/dynamic_config_manager.md
fix https://github.com/didi/Logi-KafkaManager/issues/208
> add expert config desc

- kafka-manager-console/src/container/admin/config.tsx
> 用户管理页面，前端限制用户删除自己

- kafka-manager-task/src/main/java/com/xiaojukeji/kafka/manager/task/dispatch/op/AutoHandleTopicOrder.java
- kafka-manager-task/src/main/java/com/xiaojukeji/kafka/manager/task/dispatch/op/AutomatedHandleOrder.java
- kafka-manager-web/src/main/java/com/xiaojukeji/kafka/manager/web/api/versionone/thirdpart/ThirdPartBrokerController.java
- kafka-manager-web/src/main/resources/application.yml
增加App与Topic自动化审批开关.
fix https://github.com/didi/Logi-KafkaManager/issues/226
> 增加App与Topic自动化审批开关

- kafka-manager-extends/kafka-manager-account/src/main/java/com/xiaojukeji/kafka/manager/account/impl/LoginServiceImpl.java
> In case of authentication failure, add a clear response code

- kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/service/gateway/impl/TopicConnectionServiceImpl.java
- kafka-manager-dao/src/main/java/com/xiaojukeji/kafka/manager/dao/gateway/TopicConnectionDao.java
- kafka-manager-dao/src/main/java/com/xiaojukeji/kafka/manager/dao/gateway/impl/TopicConnectionDaoImpl.java
- kafka-manager-dao/src/main/resources/mapper/TopicConnectionDao.xml
> 连接信息写DB优化为批量写入

- README.md
- docs/user_guide/faq.md
> merge master

- kafka-manager-web/pom.xml
- pom.xml
fix https://github.com/didi/Logi-KafkaManager/issues/298
> bump tomcat version to 8.5.56

- kafka-manager-console/src/container/header/index.tsx
> fix title version

- kafka-manager-web/pom.xml
- pom.xml
fix https://github.com/didi/Logi-KafkaManager/issues/298
> bump tomcat version to 8.5.66

- kafka-manager-dao/src/main/resources/mapper/HeartbeatDao.xml
- kafka-manager-task/src/main/java/com/xiaojukeji/kafka/manager/task/component/Heartbeat.java
heartbeat表的数据更新时间从MySQL自动生成调整为Logi-KM的时间
> heartbeat表的数据更新时间从MySQL自动生成调整为Logi-KM的时间

- kafka-manager-console/package.json
- kafka-manager-console/src/container/alarm/add-alarm/alarm-select.tsx
> 修复clipbord 2.0.6 打包问题

- kafka-manager-web/src/main/resources/application.yml
fix https://github.com/didi/Logi-KafkaManager/issues/314
> optimize n9e's default port

- kafka-manager-common/src/main/java/com/xiaojukeji/kafka/manager/common/utils/jmx/JmxConnectorWrap.java
fix https://github.com/didi/Logi-KafkaManager/issues/313
> fix jmx credentials

- kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/service/impl/TopicServiceImpl.java
> 修复poll异常时, 超时时间不生效问题

- pom.xml
fix https://github.com/didi/Logi-KafkaManager/issues/334
> bump jackson-databind version to 2.9.10.8

- kafka-manager-common/src/main/java/com/xiaojukeji/kafka/manager/common/constant/TopicCreationConstant.java
- kafka-manager-common/src/main/java/com/xiaojukeji/kafka/manager/common/entity/ao/topic/TopicBasicDTO.java
- kafka-manager-common/src/main/java/com/xiaojukeji/kafka/manager/common/entity/vo/normal/topic/TopicBasicVO.java
- kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/cache/PhysicalClusterMetadataManager.java
- kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/service/impl/TopicServiceImpl.java
- kafka-manager-task/src/main/java/com/xiaojukeji/kafka/manager/task/schedule/metadata/FlushTopicProperties.java
- kafka-manager-web/src/main/java/com/xiaojukeji/kafka/manager/web/api/versionone/normal/NormalTopicController.java
- kafka-manager-web/src/main/java/com/xiaojukeji/kafka/manager/web/converters/TopicModelConverter.java
> Topic基本信息中增加retention.bytes信息

- kafka-manager-extends/kafka-manager-account/src/main/java/com/xiaojukeji/kafka/manager/account/impl/LoginServiceImpl.java
> 白名单接口中仅保留登录接口

- kafka-manager-common/src/main/java/com/xiaojukeji/kafka/manager/common/constant/Constant.java
- kafka-manager-task/src/main/java/com/xiaojukeji/kafka/manager/task/dispatch/metrics/store/StoreBrokerMetrics.java
- kafka-manager-task/src/main/java/com/xiaojukeji/kafka/manager/task/dispatch/metrics/store/StoreDiDiAppTopicMetrics.java
- kafka-manager-task/src/main/java/com/xiaojukeji/kafka/manager/task/dispatch/metrics/store/StoreDiDiTopicRequestTimeMetrics.java
- kafka-manager-task/src/main/java/com/xiaojukeji/kafka/manager/task/listener/StoreCommunityTopicMetrics2DB.java
> 修复批量往DB写入空指标数组时报SQL语法异常的问题

- README.md
- kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/service/gateway/impl/GatewayConfigServiceImpl.java
> 网关增加配置及修改配置时，version不变化问题修复

- container/helm/templates/configmap.yaml
- distribution/conf/application.yml.example
- docs/install_guide/config_description.md
- kafka-manager-common/pom.xml
- kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/utils/ConfigUtils.java
- kafka-manager-dao/src/main/java/com/xiaojukeji/kafka/manager/dao/BrokerMetricsDao.java
- kafka-manager-dao/src/main/java/com/xiaojukeji/kafka/manager/dao/ClusterMetricsDao.java
- kafka-manager-dao/src/main/java/com/xiaojukeji/kafka/manager/dao/TopicAppMetricsDao.java
- kafka-manager-dao/src/main/java/com/xiaojukeji/kafka/manager/dao/TopicMetricsDao.java
- kafka-manager-dao/src/main/java/com/xiaojukeji/kafka/manager/dao/TopicRequestMetricsDao.java
- kafka-manager-dao/src/main/java/com/xiaojukeji/kafka/manager/dao/TopicThrottledMetricsDao.java
- kafka-manager-dao/src/main/java/com/xiaojukeji/kafka/manager/dao/impl/BrokerMetricsImpl.java
- kafka-manager-dao/src/main/java/com/xiaojukeji/kafka/manager/dao/impl/ClusterMetricsDaoImpl.java
- kafka-manager-dao/src/main/java/com/xiaojukeji/kafka/manager/dao/impl/TopicAppMetricsDaoImpl.java
- kafka-manager-dao/src/main/java/com/xiaojukeji/kafka/manager/dao/impl/TopicMetricsDaoImpl.java
- kafka-manager-dao/src/main/java/com/xiaojukeji/kafka/manager/dao/impl/TopicRequestMetricsDaoImpl.java
- kafka-manager-dao/src/main/java/com/xiaojukeji/kafka/manager/dao/impl/TopicThrottledMetricsDaoImpl.java
- kafka-manager-dao/src/main/resources/mapper/BrokerMetricsDao.xml
- kafka-manager-dao/src/main/resources/mapper/ClusterMetricsDao.xml
- kafka-manager-dao/src/main/resources/mapper/TopicAppMetricsDao.xml
- kafka-manager-dao/src/main/resources/mapper/TopicMetricsDao.xml
- kafka-manager-dao/src/main/resources/mapper/TopicRequestMetricsDao.xml
- kafka-manager-dao/src/main/resources/mapper/TopicThrottledMetricsDao.xml
- kafka-manager-task/src/main/java/com/xiaojukeji/kafka/manager/task/dispatch/metrics/delete/DeleteMetrics.java
- kafka-manager-task/src/main/java/com/xiaojukeji/kafka/manager/task/listener/StoreTopicThrottledMetrics2DB.java
- kafka-manager-web/src/main/resources/application.yml
- pom.xml
1. add lombok; 
2. support config delete metrics rate;
> 1.add lombok; 2.support change delete metrics rate;

- docs/dev_guide/dynamic_config_manager.md
- kafka-manager-common/src/main/java/com/xiaojukeji/kafka/manager/common/entity/ao/config/expert/TopicExpiredConfig.java
- kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/service/impl/ExpertServiceImpl.java
Ref: https://github.com/didi/LogiKM/issues/327
> 平台配置EXPIRED_TOPIC_CONFIG新增正则过滤Topic

- container/dockerfiles/Dockerfile
Dockerfile mv application.yml to fix start failed problem
> Dockerfile mv application.yml to fix start failed problem

- kafka-manager-console/src/container/header/index.tsx
- pom.xml
> 修复console模块关闭问题及前端文件名错误问题

- kafka-manager-common/src/main/java/com/xiaojukeji/kafka/manager/common/utils/BackoffUtils.java
- kafka-manager-common/src/main/java/com/xiaojukeji/kafka/manager/common/utils/jmx/JmxConfig.java
- kafka-manager-common/src/main/java/com/xiaojukeji/kafka/manager/common/utils/jmx/JmxConnectorWrap.java
增加简单回退工具类，增加Jmx连接失败回退功能机制，优化Jmx连接失败日志
> 增加简单回退工具类，增加Jmx连接失败回退功能机制，优化Jmx连接失败日志

- distribution/conf/application.yml.example
- kafka-manager-common/src/main/java/com/xiaojukeji/kafka/manager/common/constant/ApiPrefix.java
- kafka-manager-extends/kafka-manager-account/src/main/java/com/xiaojukeji/kafka/manager/account/impl/LoginServiceImpl.java
- kafka-manager-extends/kafka-manager-kcm/src/main/java/com/xiaojukeji/kafka/manager/kcm/component/agent/n9e/N9e.java
- kafka-manager-extends/kafka-manager-kcm/src/main/resources/kcm_script.sh
- kafka-manager-web/src/main/java/com/xiaojukeji/kafka/manager/web/api/versionone/thirdpart/ThirdPartBrokerController.java
- kafka-manager-web/src/main/resources/application.yml
1.安装部署脚本LogiKM可配置; 2.增加网关接口及第三方接口可直接调用的开关;
> 1.安装部署脚本LogiKM可配置; 2.增加网关接口及第三方接口可直接调用的开关;

- kafka-manager-task/src/main/java/com/xiaojukeji/kafka/manager/task/component/AbstractScheduledTask.java
- kafka-manager-web/src/main/java/com/xiaojukeji/kafka/manager/web/MainApplication.java
> 优化corn表达式解析失败后退出无任何日志提示问题

- kafka-manager-extends/kafka-manager-monitor/src/main/java/com/xiaojukeji/kafka/manager/monitor/component/n9e/N9eService.java
- kafka-manager-extends/kafka-manager-notify/src/main/java/com/xiaojukeji/kafka/manager/notify/OrderPassedNotifyService.java
- kafka-manager-extends/kafka-manager-notify/src/main/java/com/xiaojukeji/kafka/manager/notify/OrderRefusedNotifyService.java
> 允许配置文件中不进行配置

- .gitignore
- kafka-manager-extends/kafka-manager-account/src/test/java/com/xiaojukeji/kafka/manager/account/AbstractSingleSignOnTest.java
modify AbstractSingleSignOnTest error
> modify AbstractSingleSignOnTest error

- kafka-manager-common/src/main/java/com/xiaojukeji/kafka/manager/common/utils/GitPropUtil.java
- kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/utils/ConfigUtils.java
- kafka-manager-web/pom.xml
- kafka-manager-web/src/main/java/com/xiaojukeji/kafka/manager/web/config/SwaggerConfig.java
1、打包时自动生成版本信息及git提交信息；2、优化swagger对版本信息的获取；
> 1、打包时自动生成版本信息及git提交信息；2、优化swagger对版本信息的获取；

- kafka-manager-common/src/main/java/com/xiaojukeji/kafka/manager/common/entity/ao/common/FutureTaskDelayQueueData.java
- kafka-manager-common/src/main/java/com/xiaojukeji/kafka/manager/common/utils/FutureUtil.java
> 补充FutureUtil类

- README.md
> fix wrong link in readme

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/acl/impl/KafkaAclServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/change/record/impl/KafkaChangeRecordServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/cluster/impl/ClusterPhyServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/kafkauser/impl/KafkaUserServiceImpl.java
- km-dist/init/sql/ddl-ks-km.sql
> 1、删除无效字段；2、日志优化；

- docs/dev_guide/本地源码启动手册.md
> [KnowStreaming-524] fix one markdown link 404 not found

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/constant/Constant.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/broker/BrokerService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/broker/impl/BrokerMetricServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/broker/impl/BrokerServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/kafkacontroller/impl/KafkaControllerServiceImpl.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/BrokerMetricESDAO.java
> 解决raft集群controller信息不断记录问题

- km-dist/init/sql/ddl-logi-security.sql
fix https://github.com/didi/KnowStreaming/issues/523
> Modify the default value of logi_security_oplog.operation_methods

- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/BaseMetricESDAO.java
处理 https://github.com/didi/KnowStreaming/issues/563 ES 查询报错问题
> 解决 java.lang.NumberFormatException: For input string: "{"value":0,"relation":"eq"}" 问题

- docs/install_guide/版本升级手册.md
- km-dist/init/sql/ddl-logi-security.sql
fix https://github.com/didi/KnowStreaming/issues/564
> 修复日志表字段过短问题

- pom.xml
> bump version to 3.0.0-beta.4

- docs/install_guide/单机部署手册.md
1. [单机部署手册.md]docker-compose部署方式添加注释描述
2. 更改docker-compose中ui对外访问port为80
> [单机部署手册.md]docker-compose部署方式添加注释描述

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/group/GroupService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/group/impl/GroupServiceImpl.java
- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/metadata/SyncKafkaGroupTask.java
fix https://github.com/didi/KnowStreaming/issues/582
> DB中Group信息的更新方式，由replace调整为insert或update

- km-persistence/src/main/resources/mybatis/ReassignJob.xml
> [ISSUE-598]Fix start_time not set when create reassign job in MySQL-8

- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/metadata/SyncKafkaGroupTask.java
同步Group元信息时，如果Topic已经不存在了，则过滤掉该Group+Topic信息
> [ISSUE-624]过滤掉不存在的Topic(#624)

- km-dist/init/sql/ddl-ks-km.sql
[issue #666] Fix the type of role phase in ks_km_zookeeper table](https://github.com/didi/KnowStreaming/pull/669)
> fix issue: [#666]

- docs/install_guide/版本升级手册.md
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/vo/zookeeper/ClusterZookeepersOverviewVO.java
fix https://github.com/didi/KnowStreaming/issues/666
> [ISSUE-666] Error in ks_km_zookeeper table role type

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/constant/Constant.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checkresult/HealthCheckResultService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checkresult/impl/HealthCheckResultServiceImpl.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/mysql/health/HealthCheckResultDAO.java
- km-persistence/src/main/resources/mybatis/HealthCheckResultMapper.xml
- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/health/AbstractHealthCheckTask.java
[[issue #662] Fix deadlocks caused by adding data using MySQL's REPLACE method](https://github.com/didi/KnowStreaming/pull/681)
>  fix issue: [#662]

- km-console/packages/layout-clusters-fe/src/components/CardBar/index.tsx
修复时间展示有误的bug
由原先的12小时制改为24小时制
XXXX
> [ISSUE #672] 修复健康巡检结果时间展示错误的问题

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/utils/ValidateUtils.java
- km-extends/km-account/src/main/java/com/xiaojukeji/know/streaming/km/account/login/ldap/remote/LdapAuthentication.java
> [ISSUE #683]  fix ldap bug

- bin/init_es_template.sh
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/constant/ESIndexConstant.java
- km-dist/docker/manager/es_template_create.sh
- km-dist/init/template/ks_kafka_replication_metric
- km-dist/init/template/template.sh
> [ISSUE #674] 解决Replica指标的ES索引模版错误问题

- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/group/impl/GroupManagerImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/group/impl/GroupServiceImpl.java
[issue #700] Adjust the prompt and replace the Arrays.asList() with the Collections.singletonList()
> fix issue: [#700]

- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/topic/impl/OpTopicManagerImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/partition/PartitionService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/partition/impl/PartitionServiceImpl.java
修复创建完topic直接查message显示topic不存在问题。
把topic信息写入到db时候，增加延时任务，查询partition信息，写入DB。
创建topic后，过3秒查询，不会提示没有partition。
> [Bugfix] 修复新建Topic后，立即查看Topic-Messages信息会提示Topic不存在的问题 (#697)

- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/ReplicationMetricESDAO.java
- km-persistence/src/main/resources/dsl/ReplicationMetricESDAO/getAggSingleReplicationMetrics
[Bugfix] fix replica dsl (#708)
[Bugfix] fix replica dsl (#708)
> [Bugfix] fix replica dsl (#708)

- .gitignore
准备解决maven 编译${km.version}问题
增加 .gitignore内容
可以正常编译，并且maven仓库的版本号与 ${km.version} 匹配
> #732 fix: maven ${km.version} bug

- km-console/packages/layout-clusters-fe/src/pages/Consumers/index.tsx
feat:Consumer列表刷新按钮新增hover提示 #698 
1. 使用Tooltip组件给Consumer列表刷新按钮新增提示；
2. 删掉多余引用，Form组件
> [ISSUE #698 ]feat:Consumer列表刷新按钮新增hover提示

- km-console/packages/layout-clusters-fe/src/pages/TopicList/index.less
styles:消息大小测试弹框字符数显示字体调整 https://github.com/didi/KnowStreaming/issues/725
字体颜色#adb5bc变更为#74788D
> [ISSUE #725]styles:消息大小测试弹框字符数显示字体调整

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/oprecord/impl/OpLogWrapServiceImpl.java
[Bugfix] No thread-bound request found. (#743)
> [Bugfix] No thread-bound request found. (#743)

- km-console/packages/config-manager-fe/src/components/TypicalListCard/index.less
- km-console/packages/layout-clusters-fe/src/components/CardBar/BrokerHealthCheck.tsx
- km-console/packages/layout-clusters-fe/src/components/CardBar/index.less
- km-console/packages/layout-clusters-fe/src/components/ChartOperateBar/style/index.less
- km-console/packages/layout-clusters-fe/src/index.less
- km-console/packages/layout-clusters-fe/src/pages/Jobs/index.less
- km-console/packages/layout-clusters-fe/src/pages/SingleClusterDetail/index.less
styles:部分icon在hover的时候，需要有背景色 https://github.com/didi/KnowStreaming/issues/739
1.Cluster：健康度设置、编辑集群、刷新图表
2.Broker Overview：刷新图表、卡片Similar Config
3.Job：列表表头自定义列
4.Broker、Topic等等所有的列表的刷新，包括系统管理
以上icon在hover的时候，需要有背景色。
具体效果可查看：【腾讯文档】需求确认&实现
https://docs.qq.com/doc/DTHBST0VLanF4aGpU
> [ISSUE #739]styles:部分icon在hover的时候，需要有背景色

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/broker/impl/BrokerMetricServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/version/metrics/kafka/BrokerMetricVersionItems.java
> [Bugfix]修复Broker列表LogSize指标存储时名称错误的问题(#759)

- km-console/packages/layout-clusters-fe/src/pages/TopicList/index.tsx
[Feat]Topic列表健康分修改为健康状态(https://github.com/didi/KnowStreaming/issues/758)
> [Feat]Topic列表健康分修改为健康状态(#758)

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/zookeeper/HealthCheckZookeeperService.java
optimize zk OutstandingRequests checker’s exception log
optimize zk OutstandingRequests checker’s exception log
> [Optimize] optimize zk OutstandingRequests checker’s exception log (#738)

- docs/dev_guide/无数据排查文档.md
> [Doc]增加无数据排查文档(#773)

- km-console/packages/layout-clusters-fe/src/pages/MutliClusterPage/AccessCluster.tsx
close https://github.com/didi/KnowStreaming/issues/754
优化接入集群时，集群配置不写时， 校验参数报错
优化接入集群时，集群配置不写时， 校验参数报错 
XXXX
> [Optimized] 优化接入集群时，集群配置不写时， 校验参数报错 

- km-console/packages/layout-clusters-fe/src/pages/TopicDetail/Messages.tsx
更改文案
[Optimize]更新Topic-Messages抽屉文案(#771)
XXXX
> [Optimize]更新Topic-Messages抽屉文案(#771)

- km-collector/src/main/java/com/xiaojukeji/know/streaming/km/collector/service/CollectThreadPoolService.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/utils/FutureNoWaitUtil.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/utils/FutureUtil.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/utils/FutureWaitUtil.java
- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/service/TaskThreadPoolService.java
> [Optimize]优化线程池的名称(#789)

- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/kafka/KafkaJMXClient.java
> [Bugfix]修复KafkaJMXClient类中logger错误的问题(#794)

- km-collector/src/main/java/com/xiaojukeji/know/streaming/km/collector/metric/kafka/ReplicaMetricCollector.java
> [Bugfix]修复ReplicaMetricCollector编译失败问题(#802)

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/topic/TopicConfig.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/po/topic/TopicPO.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/converter/TopicConverter.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/topic/TopicService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/topic/impl/TopicConfigServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/topic/impl/TopicServiceImpl.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/mysql/topic/TopicDAO.java
- km-persistence/src/main/resources/mybatis/TopicMapper.xml
- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/kafka/metadata/SyncTopicConfigTask.java
> [Optimize]优化Topic元信息更新策略(#806)

- km-console/packages/layout-clusters-fe/src/pages/Zookeeper/Sider.tsx
closed https://github.com/didi/KnowStreaming/issues/793
更新文案
更新Zookeeper详情目录结构搜索文案
XXXX
> [Optimize]更新Zookeeper详情目录结构搜索文案(#793)

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/zookeeper/fourletterword/parser/MonitorCmdDataParser.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/zookeeper/fourletterword/parser/ServerCmdDataParser.java
增加遗漏的指标名的处理，减少warn日志该部分的信息。
Fix #805
> [Optimize]ZK四字命令解析日志优化(#805)

- km-rest/src/main/java/com/xiaojukeji/know/streaming/km/rest/config/LogiSecurityDataSourceConfig.java
修复logi-securiy模块数据库选择错误
增加logi-securiy模块数据配置类。
XXXX
> [Bug]修复logi-securiy模块数据库选择错误

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/reassign/impl/ReassignJobServiceImpl.java
修复迁移任务状态不一致问题
优先副本选举失败，不会进行事物回滚。
XXXX
> [Bugfix]修复迁移任务状态不一致问题(#815)

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/vo/metrics/point/MetricPointVO.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/version/BaseMetricService.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/ESTPService.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/BaseMetricESDAO.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/BrokerMetricESDAO.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/ClusterMetricESDAO.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/GroupMetricESDAO.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/TopicMetricESDAO.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/connect/ConnectClusterMetricESDAO.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/connect/ConnectorMetricESDAO.java
- km-rest/src/main/resources/application.yml
1、复用线程池，同时支持线程池的线程数可配置；
2、优化查询TopN指标时，可能会出现重复查询的问题；
3、处理代码扫描(SonarLint)反馈的问题；
Fix #823
> [Optimize]Overview页面的TopN查询ES流程优化(#823)

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/reassign/ReassignResult.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/utils/CommonUtils.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/reassign/impl/ReassignJobServiceImpl.java
> [Bugfix]修复job更新中的数组越界报错(#744)

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/connector/impl/ConnectorMetricServiceImpl.java
修复connector指标采集算最大值错误
更新指标采集最大值的计算
XXXX
> [Bugfix]connector指标采集算最大值错误(#836)

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/connector/impl/ConnectorMetricServiceImpl.java
修复函数映射错误
修改为正确的doNothong函数映射
XXXX
> [Bugfix]修复函数映射错误

- docs/install_guide/版本升级手册.md
- km-dist/init/sql/ddl-logi-security.sql
> [Bugfix]修复用户更新失败问题

- kafka-manager-console/src/container/drawer/data-migration.tsx
修复2.6版本 批量数据迁移的bug  issue: https://github.com/didi/KnowStreaming/issues/785
修复data-migration.tsx 获取index、key方式
改动很小，本地已经测试过，没问题
> [ISSUE #785]  fix can not submit batch data migration task when topic's count is over 10

- km-collector/src/main/java/com/xiaojukeji/know/streaming/km/collector/metric/connect/ConnectConnectorMetricCollector.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/version/metrics/connect/ConnectorMetricVersionItems.java
修复connector指标筛选缺少指标的问题
增加缺少的指标。
XXXX
> [Bugfix]修复connector指标筛选缺少指标的问题

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/topic/HealthCheckTopicService.java
> [Optimize]优化Topic健康巡检的日志(#855)

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/partition/impl/PartitionServiceImpl.java
> [Bugfix]修复查看消息时，选择分区不生效问题(#858)

- docs/install_guide/版本升级手册.md
> [Bugfix]修复用户信息修改后，用户列表会抛出空指针异常的问题(#860)

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/broker/impl/BrokerMetricServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/replica/impl/ReplicaMetricServiceImpl.java
> [Bugfix]修复采集副本指标时，参数传递错误问题(#867)

- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/version/impl/VersionControlManagerImpl.java
> [Optimize]ZK-Overview页面补充默认展示的指标(#874)

- docs/user_guide/faq.md
> [Optimize]补充Ldap登录的配置说明(#888)

- docs/user_guide/faq.md
补充Testcontainers的使用说明(#890)
补充Testcontainers的使用说明
补充Testcontainers的使用说明
> [Optimize]补充Testcontainers的使用说明(#890)

- km-collector/src/main/java/com/xiaojukeji/know/streaming/km/collector/metric/connect/mm2/MirrorMakerMetricCollector.java
- km-collector/src/main/java/com/xiaojukeji/know/streaming/km/collector/sink/mm2/MirrorMakerMetricESSender.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/connect/connector/KSConnector.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/connect/mm2/MirrorMakerTopic.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/metrics/mm2/MirrorMakerMetrics.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/metrics/mm2/MirrorMakerTopicPartitionMetrics.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/param/metric/connect/mm2/MirrorMakerMetricParam.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/event/metric/mm2/MirrorMakerMetricEvent.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/po/connect/ConnectorPO.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/po/metrice/mm2/MirrorMakerMetricPO.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/jmx/JmxAttribute.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/jmx/JmxName.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/connector/impl/ConnectorMetricServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/mm2/MirrorMakerMetricService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/mm2/MirrorMakerService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/mm2/impl/MirrorMakerMetricServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/mm2/impl/MirrorMakerServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/version/metrics/connect/MirrorMakerMetricVersionItems.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/connect/BaseConnectorMetricESDAO.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/connect/connector/ConnectorMetricESDAO.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/connect/mm2/MirrorMakerMetricESDAO.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dsls/DslConstant.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/template/TemplateConstant.java
- km-persistence/src/main/resources/es/template/ks_kafka_connect_mirror_maker_metric
- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/connect/mm2/metrics/MirrorMakerCollectorTask.java
1、[[Feature]MM2管理-读写ES中的MM2指标](https://github.com/didi/KnowStreaming/commit/44d159842648071778e41aaff2359969c9d26e2d)
2、[[Feature]MM2管理-采集MM2指标](https://github.com/didi/KnowStreaming/commit/bbf867dc5276094ce9d5d44de0cce1f85e41f914)
3、[[Feature]MM2管理-采集MM2指标任务](https://github.com/didi/KnowStreaming/commit/65ed14516f7bfd6de4a4e6de910e79e3a197f619)
> 1、MM2管理-读写ES中的MM2指标；2、MM2管理-采集MM2指标；3、MM2管理-采集MM2指标任务；

- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/cluster/impl/ClusterTopicsManagerImpl.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/dto/ha/mirror/MirrorTopicCreateDTO.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/dto/ha/mirror/MirrorTopicDeleteDTO.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/ha/HaActiveStandbyRelation.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/po/ha/HaActiveStandbyRelationPO.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/vo/cluster/res/ClusterPhyTopicsOverviewVO.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/vo/ha/mirror/TopicMirrorInfoVO.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/constant/Constant.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/converter/TopicVOConverter.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/enums/ha/HaResTypeEnum.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/enums/version/VersionEnum.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/utils/VersionUtil.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/flusher/DatabaseDataFlusher.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/ha/HaActiveStandbyRelationService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/ha/impl/HaActiveStandbyRelationServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/topic/impl/OpTopicServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/topic/impl/TopicMetricServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/version/fe/FrontEndControlVersionItems.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/version/metrics/kafka/TopicMetricVersionItems.java
- km-enterprise/km-ha/pom.xml
- km-enterprise/km-ha/src/main/java/com/xiaojukeji/know/streaming/km/ha/mirror/service/MirrorTopicService.java
- km-enterprise/km-ha/src/main/java/com/xiaojukeji/know/streaming/km/ha/mirror/service/impl/MirrorTopicServiceImpl.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/cache/DataBaseDataLocalCache.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/mysql/ha/HaActiveStandbyRelationDAO.java
- km-rest/pom.xml
- km-rest/src/main/java/com/xiaojukeji/know/streaming/km/rest/api/v3/enterprise/mirror/MirrorTopicController.java
- pom.xml
1、[[Feature]HA-滴滴Kafka版本信息兼容](https://github.com/didi/KnowStreaming/commit/824b65989382d8f094f6f410a1471f66950f9819)；
2、[[Feature]HA-镜像Topic管理](https://github.com/didi/KnowStreaming/commit/a21a3322187576c19c2a643ed2c3ea073dbb5430)；
> 1、HA-滴滴Kafka版本信息兼容；2、HA-镜像Topic管理；

- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/cluster/MultiClusterPhyManager.java
- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/cluster/impl/MultiClusterPhyManagerImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checkresult/impl/HealthCheckResultServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/state/impl/HealthStateServiceImpl.java
- km-rest/src/main/java/com/xiaojukeji/know/streaming/km/rest/api/v3/cluster/MultiClusterPhyController.java
> [Bugfix]修复正常情况下，集群状态统计错误的问题(#865)

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/cluster/HealthCheckClusterService.java
优化错误日志，明确错误原因
当通过es获取的activeControllerCount指标为null时，优化错误日志
当通过es获取的activeControllerCount指标为null时错误日志为get metrics failed, activeControllerCount is null。。。
> [Optimize]健康检查日志优化(#869)

- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/cluster/impl/ClusterBrokersManagerImpl.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/constant/KafkaConstant.java
> [Bugfix]修复 Broker Similar Config 显示错误的问题(#872)

- km-console/packages/layout-clusters-fe/src/components/CardBar/ZookeeperCard.tsx
- km-console/packages/layout-clusters-fe/src/components/CardBar/index.less
> [Bugfix]zookeeper页面leader节点显示异常(#873)

- km-console/packages/layout-clusters-fe/src/pages/MirrorMaker2/AddMM2JSON.tsx
> [Optimize] JSON新增MM2 Drawer Title文案变更(#894)

- km-console/packages/layout-clusters-fe/src/components/CardBar/index.tsx
- km-console/packages/layout-clusters-fe/src/pages/SingleClusterDetail/config.tsx
> [Optimize] 健康检查项时间和结果显示(#930)

- CODE_OF_CONDUCT.md
> [Bugfix]订正失效的邮箱地址(#944)

- km-console/packages/layout-clusters-fe/src/pages/ConnectDashboard/index.tsx
> [Bugfix] 修复打包不成功(#940)

- distribution/conf/create_mysql_table.sql
>  HA-添加高可用相关表结构

- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/kafka/zookeeper/service/impl/KafkaZKDAOImpl.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/kafka/zookeeper/znode/brokers/BrokerMetadata.java
> [Bugfix]修复Broker元信息解析方法未调用导致接入集群失败的问题(#986)

- pom.xml
> bump jackson version to 2.13.5

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/po/group/GroupMemberPO.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/po/group/GroupPO.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/converter/GroupConverter.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/group/GroupService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/group/impl/GroupServiceImpl.java
- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/kafka/metadata/SyncKafkaGroupTask.java
1、Group元信息未变化时，则不进行updateById操作；
2、失效的Group信息直接删除；
Fix #1005
> [Optimize]Group元信息更新优化(#1005)

- km-extends/km-monitor/src/main/java/com/xiaojukeji/know/streaming/km/monitor/component/AbstractMonitorSinkService.java
> [Bugfix]修复Prometheus开放接口中，Partition指标tag缺失的问题(#1013)

- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/BaseMetricESDAO.java
> [Bugfix]修复es索引create/delete死循环 (#1021)

- docs/install_guide/版本升级手册.md
- km-persistence/src/main/resources/sql/dml-logi.sql
> [Optimize]Connector增加重启、编辑、删除等权限点

- km-console/packages/layout-clusters-fe/src/pages/ConsumerGroup/ResetOffsetDrawer.tsx
- km-console/packages/layout-clusters-fe/src/pages/Consumers/ResetOffsetDrawer.tsx
- km-console/packages/layout-clusters-fe/src/pages/TopicDetail/ResetOffsetDrawer.tsx
> [Bugfix]消费组不支持重置到最旧Offset的问题 (#1039)

- docs/install_guide/版本升级手册.md
- km-persistence/src/main/resources/sql/dml-logi.sql
1、补充Security模块-ACL相关权限点；
2、补充Security模块-User相关权限点；
> [Bugfix]修复Security模块，后端权限点缺失问题

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/jmx/JmxConnectorWrap.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/connect/ConnectJMXClient.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/kafka/KafkaJMXClient.java
1、统一Jmx客户端相关日志格式；
2、增加创建的Jmx-Connector时，所使用的信息；
3、优化日志级别；
> [Optimize]Jmx相关日志优化

- docs/install_guide/版本升级手册.md
- km-persistence/src/main/resources/sql/dml-logi.sql
> [Bugfix]增加查看User密码的权限点

- km-extends/km-account/src/main/java/com/xiaojukeji/know/streaming/km/account/login/ldap/LdapLoginServiceImpl.java
fix NPE issue #1035
NPE solved
> [Bugfix] fix ldap user.getId() NPE (#1035)

- km-console/packages/layout-clusters-fe/src/api/index.ts
- km-console/packages/layout-clusters-fe/src/pages/ConsumerGroup/Delete.tsx
- km-console/packages/layout-clusters-fe/src/pages/ConsumerGroup/Detail.tsx
- km-console/packages/layout-clusters-fe/src/pages/ConsumerGroup/config.tsx
- km-console/packages/layout-clusters-fe/src/pages/ConsumerGroup/index.tsx
> [Feature]新增删除Group或GroupOffset功能(#1040)

- km-console/packages/layout-clusters-fe/src/api/index.ts
- km-console/packages/layout-clusters-fe/src/pages/TopicList/index.tsx
> [Feature]增加Truncate数据功能(#1043)

- km-console/packages/layout-clusters-fe/src/pages/CommonConfig.tsx
- km-console/packages/layout-clusters-fe/src/pages/Connect/config.tsx
- km-console/packages/layout-clusters-fe/src/pages/Connect/index.tsx
> [Optimize]Connect操作未接入权限管理，所有用户都可以重启、编辑、删除(#1050)

- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/cluster/ClusterBrokersManager.java
- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/cluster/impl/ClusterBrokersManagerImpl.java
- km-rest/src/main/java/com/xiaojukeji/know/streaming/km/rest/api/v3/cluster/ClusterBrokersController.java
> [Optimize]优化集群Brokers中, Controller显示存在延迟的问题

- km-console/packages/config-manager-fe/config/webpack.common.js
> [Optimize]优化系统管理子应用无法正常启动(#1159)

- km-console/packages/layout-clusters-fe/package.json
- km-console/packages/layout-clusters-fe/src/pages/ConsumerGroup/ExpandedRow.tsx
- km-console/packages/layout-clusters-fe/src/pages/ConsumerGroup/ResetOffsetDrawer.tsx
- km-console/packages/layout-clusters-fe/src/pages/TopicDetail/ConsumerGroupDetail.tsx
- km-console/packages/layout-clusters-fe/src/pages/TopicDetail/ResetOffsetDrawer.tsx
修复消费组Offset重置后，提示重置成功，但是前端不刷新数据，Offset无变化的问题
使用pubsub-js解决问题
> [Bugfix]修复消费组Offset重置后，提示重置成功，但是前端不刷新数据，Offset无变化的问题

- docs/dev_guide/指标说明.md
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/version/metrics/kafka/ClusterMetricVersionItems.java
[Bugfix] 修复Overview指标文字错误 (#1150)
> [Bugfix] 修复Overview指标文字错误 (#1150)

- km-console/packages/layout-clusters-fe/src/pages/ConsumerGroup/Detail.tsx
- km-console/packages/layout-clusters-fe/src/pages/ConsumerGroup/ExpandedRow.tsx
- km-console/packages/layout-clusters-fe/src/pages/ConsumerGroup/ResetOffsetDrawer.tsx
XXXXX
- [Bugfix]修复重置offset接口调用过多问题
- [Bugfix]修复消费组Offset重置后，提示重置成功，但是前端不刷新数据，Offset无变化的问题
- [Optimize]消费组详情控制数据实时刷新
XXXX
XXXXX
XX
XXXX
> 合并主分支 (#1199)

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/enums/version/VersionEnum.java
> [Optimize]补充Kafka版本列表

- docs/dev_guide/MYSQL密码加密手册.md
- km-rest/pom.xml
添加MYSQL密码加密手册
在pom中加入了jasypt用于加密
XX
XXXX
> [DOC]添加MYSQL密码加密手册

- km-console/packages/layout-clusters-fe/src/pages/TopicList/ExpandPartition.tsx
- km-persistence/src/main/resources/es/dsl/TopicMetricESDAO/getAggListMetrics
1：topic维度的查询BytesIn，BytesOut 聚合类型应该是 sum 不能是 avg
2：getAggListMetrics dsl需要加上 brokerAgg = 1的条件
> [Bugfix]fix Topic level metric query
