- Dockerfile
- docker-compose.yml
- docker/kafka-manager/Dockerfile
- docker/kafka-manager/application-standalone.yml
- docker/kafka-manager/application.yml
- docker/mysql/Dockerfile
- docker/mysql/create_mysql_table.sql
增加容器化部署模式
1. kafka-manager独立部署模式
独立部署请自行准备MySQL数据库，并修改 ./docker/kafka-manager/application-standalone.yml中数据库连接信息后进行构建
``` bash
mvn install
docker build -f Dockerfile -t kafka-manager .
docker run -p 8080:8080 --name kafka-manager-standalone kafka-manager
```
2. kafka-manager+MySQL compose编排部署模式
``` bash
mvn install
docker-compose -f docker-compose.yml build
docker-compose -f docker-compose.yml up -d
```
> 增加docker及docker-compose部署方式

- kafka-manager-common/src/main/java/com/xiaojukeji/kafka/manager/common/constant/ApiPrefix.java
- kafka-manager-extends/kafka-manager-account/src/main/java/com/xiaojukeji/kafka/manager/account/LoginService.java
- kafka-manager-extends/kafka-manager-account/src/main/java/com/xiaojukeji/kafka/manager/account/impl/LoginServiceImpl.java
- kafka-manager-web/src/main/java/com/xiaojukeji/kafka/manager/web/inteceptor/PermissionInterceptor.java
通过获取类的RequestMapping注解来判断当前请求是否需要登录，避免无序的HTTP请求导致部分接口登录检查被绕过
> 通过获取类的RequestMapping注解来判断当前请求是否需要登录

- pom.xml
bump jetty-util version to 9.4.39.v20210325
fix https://github.com/didi/Logi-KafkaManager/issues/269
> bump jetty-util version to 9.4.39.v20210325

- kafka-manager-web/pom.xml
- pom.xml
移除原logback-1.2.3
更新为:1.2.9
关于logback的漏洞:[详见这里](https://nvd.nist.gov/vuln/detail/CVE-2021-42550)
> 关于logback的版本漏洞修复 #488

- docs/user_guide/faq.md
[Jmx 连接配置&问题解决 #664](https://github.com/didi/KnowStreaming/issues/664)
修复正确的超链接
修复正确的超链接为[JMX-连接失败问题解决](https://doc.knowstreaming.com/product/9-attachment#91jmx-%E8%BF%9E%E6%8E%A5%E5%A4%B1%E8%B4%A5%E9%97%AE%E9%A2%98%E8%A7%A3%E5%86%B3)
跳转访问 OK
> [ISSUE #664]关于'JMX-连接失败问题解决'的超链接修复

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/zookeeper/fourletterword/MonitorCmdData.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/zookeeper/fourletterword/ServerCmdData.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/zookeeper/fourletterword/parser/MonitorCmdDataParser.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/zookeeper/fourletterword/parser/ServerCmdDataParser.java
fix ISSUE #678 
1. 调整ServerCmdData,MonitorCmdData类中zkAvgLatency字段类型为Float
> [ISSUE #678] zk-Latency avg为多位小数会抛出空指针

- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/BrokerMetricESDAO.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/ClusterMetricESDAO.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/GroupMetricESDAO.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/TopicMetricESDAO.java
- km-rest/src/test/java/com/xiaojukeji/know/streaming/km/persistence/es/ClusterMetricESDAOTest.java
- km-rest/src/test/java/com/xiaojukeji/know/streaming/km/persistence/es/ReplicationMetricESDAOTest.java
- km-rest/src/test/java/com/xiaojukeji/know/streaming/km/persistence/es/TopicMetricESDAOTest.java
修复ks-manager重启会导致部分信息采集抛出空指针
#677 
1. 调整`BrokerMetricESDAO.java` `ClusterMetricESDAO.java` `GroupMetricESDAO.java` `TopicMetricESDAO.java`中对指标空值的处理
2. 添加对应测试方法
后台不抛出异常，页面展示时该段时间数据缺失
> [ISSUE #677]ks-manager重启会导致部分信息采集抛出空指针

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/cache/ZookeeperLocalCache.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/zookeeper/impl/ZookeeperMetricServiceImpl.java
1、避免不同集群，相同的ZK地址时，指标重复获取的情况；
2、避免集群某个ZK地址获取指标失败时，下一个周期还会继续尝试从该地址获取指标；
> [Optimize] 优化ZK指标的获取，减少重复采集的出现 (#709)

- km-collector/src/main/java/com/xiaojukeji/know/streaming/km/collector/metric/ReplicaMetricCollector.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/cache/CollectedMetricsLocalCache.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/broker/impl/BrokerMetricServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/replica/ReplicaMetricService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/replica/impl/ReplicaMetricServiceImpl.java
- km-rest/src/main/java/com/xiaojukeji/know/streaming/km/rest/api/v3/replica/ReplicaMetricsController.java
- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/metrics/ReplicaMetricCollectorTask.java
1、当集群存在较多副本时，指标采集的性能会严重降低；
2、Replica的指标基本上都是在实时获取时才需要，因此当前先将Replica指标采集任务关闭，后续依据产品需要再看是否开启；
> [Optimize] 删除Replica指标采集任务

- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/cluster/impl/ClusterBrokersManagerImpl.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/vo/cluster/res/ClusterBrokersOverviewVO.java
1、当前页面无数据时，一部分的原因是JMX连接失败导致；
2、Broker列表中增加是否连接成功的信息，便于问题的排查；
> [Optimize] 集群Broker列表中，补充Jmx是否成功连接的信息

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/reassign/ReassignResult.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/reassign/impl/ReassignJobServiceImpl.java
修复 preferredReplicaElection 方法未能如预期调用的问题 #248
reassignStateMap 中的
增加了迁移前 ISR 列表的首个 broker 与迁移后 ISR 列表的首个 broker 判别，若不同则触发优选副本切换为分区 leader
> [fix]Repair that preferredReplicaElection is not called as expected #248

- km-console/packages/layout-clusters-fe/src/app.tsx
Fix: #718 
优化：在平台上面增加显示具体的版本的功能
在鼠标移动到右上角头像的时候，会出现下拉选项，当前只有一个 "登出"。我们可以在 "登出"上面添加一个下拉项 "版本说明"，该选项为一个链接，会链接到github的[Releases](https://github.com/didi/KnowStreaming/releases)
在鼠标移动到右上角头像的时候，会出现下拉选项，我们可以看到 “版本说明”项，该选项为一个链接，会链接到github的[Releases](https://github.com/didi/KnowStreaming/releases)
> For #718, 增加平台版本说明功能

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/broker/impl/BrokerConfigServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/topic/impl/TopicConfigServiceImpl.java
Kafka v2.3增加了增量修改配置的功能，但是KS中错误的将其配置为0.11.0版本就具备该能力，因此对其进行调整。
Fix #762
> [Bugfix]修复Broker&Topic修改时，版本设置错误问题(#762)

- km-rest/pom.xml
- pom.xml
There are 1 security vulnerabilities found in org.springframework:spring-context 5.3.18
- [CVE-2022-22968](https://www.oscs1024.com/hd/CVE-2022-22968)
Upgrade org.springframework:spring-context from 5.3.18 to 5.3.19 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
Signed-off-by:pen4<948453219@qq.com>
> fix(sec): upgrade org.springframework:spring-context to 5.3.19

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/version/fe/FrontEndControlVersionItems.java
[Bugfix]修复创建topic选择过期策略(kafka版本0.10.1.0之前)compact和delete只能二选一(didi#770)
主要完成后端部分，前端部分待前端比较熟悉的同学完善下
> [Bugfix]修复创建topic选择过期策略(kafka版本0.10.1.0之前)compact和delete只能二选一(didi#770)

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/health/HealthCheckAggResult.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/health/HealthScoreResult.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/vo/health/HealthScoreBaseResultVO.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/converter/HealthScoreVOConverter.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/enums/health/HealthCheckDimensionEnum.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/cache/DataBaseDataLocalCache.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/flusher/DatabaseDataFlusher.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/AbstractHealthCheckService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/broker/HealthCheckBrokerService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/group/HealthCheckGroupService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/topic/HealthCheckTopicService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/zookeeper/HealthCheckZookeeperService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checkresult/HealthCheckResultService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checkresult/impl/HealthCheckResultServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/state/HealthStateService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/state/impl/HealthStateServiceImpl.java
- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/kafka/health/AbstractHealthCheckTask.java
- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/kafka/health/TopicHealthCheckTask.java
1、增加缓存，减少健康状态指标计算时的IO；
2、健康巡检调整为按照资源维度并发处理；
3、明确HealthCheckResultService和HealthStateService的功能边界；
> [Optimize]优化健康巡检相关指标的计算(#726)

- km-console/packages/layout-clusters-fe/src/pages/TopicList/config.tsx
- km-console/packages/layout-clusters-fe/src/pages/TopicList/index.tsx
集群Topic列表健康状态对应关系存在问题，导致当健康状态指标存在时，会出现白屏。
Fix #819
> [Bugfix]修复集群Topic列表页面白屏问题(#819)

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/vo/health/HealthScoreBaseResultVO.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/AbstractHealthCheckService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/broker/HealthCheckBrokerService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/cluster/HealthCheckClusterService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/connect/HealthCheckConnectClusterService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/connect/HealthCheckConnectorService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/group/HealthCheckGroupService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/topic/HealthCheckTopicService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/zookeeper/HealthCheckZookeeperService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/state/HealthStateService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/state/impl/HealthStateServiceImpl.java
- km-rest/src/main/java/com/xiaojukeji/know/streaming/km/rest/api/v3/health/KafkaHealthController.java
> [Optimize]无ZK模块时，巡检详情忽略对ZK的展示(#764)

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/config/ZKConfig.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/kafka/KafkaAdminZKClient.java
1、修复在ks_km_physical_cluster表的zk_properties字段填写ZK 客户端的相关配置后，不生效的问题。 
2、删除zk_properties字段中，暂时无需使用的jmxConfig字段。
Fix #694
> [Bugfix]修复对ZK客户端进行配置后不生效的问题(#694)

- km-console/packages/layout-clusters-fe/src/pages/ConsumerGroup/ExpandedRow.tsx
修复“group消费topic的partition显示不全”问题
修改分页显示问题
经过修复后，可以正常显示多页的partition数据。
> [Bugfix]修复“group消费topic的partition显示不全”问题(#781)

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/flusher/DatabaseDataFlusher.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/cluster/impl/ClusterMetricServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checkresult/impl/HealthCheckResultServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/partition/impl/PartitionServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/topic/impl/TopicMetricServiceImpl.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/cache/DataBaseDataLocalCache.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/TopicMetricESDAO.java
1、将ES排序调整为基于本地cache的排序；
2、将database的本地cache从core模块移动到persistence模块；
> [Bugfix]修复Topic指标大盘获取TopN指标存在错误的问题(#896)

- km-console/packages/layout-clusters-fe/src/pages/CommonRoute.tsx
- km-console/packages/layout-clusters-fe/src/pages/TopicList/Create.tsx
根据情况区分新增Topic时的清理策略是单选还是多选
更新新增Topic时的清理策略
XXXX
> [Optimize]新增Topic时清理策略区分单选多选(#770)

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/zookeeper/fourletterword/MonitorCmdData.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/zookeeper/fourletterword/ServerCmdData.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/zookeeper/fourletterword/parser/MonitorCmdDataParser.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/zookeeper/fourletterword/parser/ServerCmdDataParser.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/zookeeper/impl/ZookeeperMetricServiceImpl.java
1.zk_min_latency、zk_max_latency指标数据类型变更为float
2.使用ConvertUtil.string2Float()方法进行string到float到类型转换
> [Bugfix]解决在解析命令执行后返回指标的值时发生的数据类型转换错误与指标存储上报时报空指针的问题

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/flusher/zk/handler/ControllerNodeChangeHandler.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/kafkacontroller/KafkaControllerService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/kafkacontroller/impl/KafkaControllerServiceImpl.java
- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/kafka/metadata/SyncControllerTask.java
问题原因：
1、新接入的集群，DB中暂未存储Broker信息，因此在存储Controller至DB时，查询DB中的Broker会查询为空。
解决方式：
1、存储Controller至DB前，主动获取一次Broker的信息。
> [Bugfix]修复新接入的集群，Controller-Host不显示的问题(#927)

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/health/checker/zookeeper/HealthCheckZookeeperService.java
[Bugfix]ZK健康巡检日志不清晰导致问题难定位 #904
> [Bugfix]ZK健康巡检日志不清晰导致问题难定位 #904

- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/connect/mm2/impl/MirrorMakerManagerImpl.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/utils/ApiCallFutureWaitUtil.java
> [Bugfix]修复mm2列表请求超时(#949)

- distribution/conf/create_mysql_table.sql
>  HA-添加高可用相关表结构

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/partition/impl/OpPartitionServiceImpl.java
fix issue [987](https://github.com/didi/KnowStreaming/issues/987)
更新任务状态时要执行leader重选，一部分leader重选失败，导致集群均衡任务状态无法更新。
修复方法：leader重选报错ElectionNotNeededException: Leader election not needed for topic partition时，可以认为无需执行重选，直接忽略该异常即可。
> [Bugfix]leader重选时忽略ElectionNotNeededException异常，返回成功

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/utils/kafka/KSPartialKafkaAdminClient.java
1、先尝试使用IncrementalCooperativeConnectProtocol协议进行解析； 
2、IncrementalCooperativeConnectProtocol协议解析失败后，再维持原先的情况，使用ConnectProtocol协议进行解析；
Fix #1010
> [Bugfix]修复Connect-GroupDescription解析失败的问题(#1010)

- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/version/impl/VersionControlManagerImpl.java
1. 解决了Connect模块没有默认勾选指标；
2. 提供Connect Cluster和Connector默认勾选指标；
|          Connect Cluster          |           Connector            |
| :-------------------------------: | :----------------------------: |
|          ConnectorCount           |          HealthState           |
|             TaskCount             |       HealthCheckPassed        |
|   ConnectorStartupAttemptsTotal   |        HealthCheckTotal        |
| ConnectorStartupFailurePercentage | CollectMetricsCostTimeUnitSec  |
|   ConnectorStartupFailureTotal    |    ConnectorTotalTaskCount     |
|     TaskStartupAttemptsTotal      |   ConnectorRunningTaskCount    |
|   TaskStartupFailurePercentage    |    ConnectorFailedTaskCount    |
|      TaskStartupFailureTotal      | …
> [Optimize]解决Connect模块没有默认勾选指标（#926）

- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/cluster/impl/ClusterBrokersManagerImpl.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/broker/Broker.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/config/JmxAuthConfig.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/config/JmxConfig.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/jmx/ServerIdJmxPort.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/enums/jmx/JmxEnum.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/jmx/JmxConnectorWrap.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/broker/impl/BrokerServiceImpl.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/connect/ConnectJMXClient.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/kafka/KafkaJMXClient.java
变更事项：
1、接入集群时，支持按照Broker粒度进行Jmx端口的配置；
2、设置Jmx端口的优先级为：指定Broker端口 》ZK中获取到的Broker端口 》指定Cluster端口；
补充说明：
1、该修改仅为后端修改，产品上暂未进行修改；
> [Feature]支持指定Server的具体Jmx端口(#965)

- pom.xml
支持MDC，方便用户接入链路追踪系统也可以在logback.xml中json格式化日志。
pom.xml文件中引入logstash-logback-encoder.jar包
`
<encoder charset="utf-8" class="net.logstash.logback.encoder.LogstashEncoder">
<includeCallerData>true</includeCallerData>
<includeMdcKeyName>springAppName</includeMdcKeyName>
<includeMdcKeyName>traceId</includeMdcKeyName>
<includeMdcKeyName>spanId</includeMdcKeyName>
<includeMdcKeyName>parentSpanId</includeMdcKeyName>
<customFields>{"system": "know-streaming"}
</customFields>
</encoder>`
在logback-spring.xml中加入以上encoder后即可支持链路追踪功能。
jar包兼容性及功能已测试通过。
> 日志输出增加支持MDC #1031

- km-console/packages/layout-clusters-fe/src/api/index.ts
- km-console/packages/layout-clusters-fe/src/pages/SecurityACLs/EditDrawer.tsx
修复权限ACL管理中，消费组列表展示错误的问题
1.消费组列表里面展示的是Group列表
2.并像生产组一样判断Group是否存在
消费组：
代码修改后效果图：
> [Bugfix]修复权限ACL管理中，消费组列表展示错误的问题(#991)

- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/topic/OpTopicManager.java
- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/topic/impl/OpTopicManagerImpl.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/param/topic/TopicTruncateParam.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/constant/KafkaConstant.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/enums/operaterecord/OperationEnum.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/topic/OpTopicService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/topic/impl/OpTopicServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/version/fe/FrontEndControlVersionItems.java
- km-rest/src/main/java/com/xiaojukeji/know/streaming/km/rest/api/v3/topic/TopicController.java
增加Truncate数据功能(didi#1043)
目前已经完成后端部分，前端待补充
> [Feature]增加Truncate数据功能(didi#1043)

- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/group/GroupManager.java
- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/group/impl/GroupManagerImpl.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/dto/group/GroupOffsetDeleteDTO.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/param/group/DeleteGroupParam.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/param/group/DeleteGroupTopicParam.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/param/group/DeleteGroupTopicPartitionParam.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/param/group/GroupParam.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/enums/group/DeleteGroupTypeEnum.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/enums/version/VersionItemTypeEnum.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/group/OpGroupService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/group/impl/OpGroupServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/version/fe/FrontEndControlVersionItems.java
- km-rest/src/main/java/com/xiaojukeji/know/streaming/km/rest/api/v3/group/GroupController.java
不包括前端，后端新增
1、新增Group删除功能；
2、新增Group-Topic纬度Offset删除功能；
3、新增Group-Topic-Partition纬度Offset删除功能；
> [Feature]新增删除Group或GroupOffset功能

- docs/user_guide/faq.md
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/worker/impl/WorkerServiceImpl.java
- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/kafka/metadata/SyncConnectClusterAndWorkerTask.java
1、FAQ中补充JMX连接失败的说明；
2、修复Connect-Worker Jmx不生效的问题；
> [Bugfix]修复Connect-Worker Jmx不生效的问题

- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/connect/mm2/impl/MirrorMakerManagerImpl.java
- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/topic/impl/TopicStateManagerImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/utils/ApiCallThreadPoolService.java
- km-rest/src/main/java/com/xiaojukeji/know/streaming/km/rest/api/v3/topic/TopicStateController.java
问题：
leader=-1的分区获取offset信息时，耗时时间过久会导致前端超时，进而整个页面的数据都获取不到；
解决：
后端主动在前端超时前，对一些请求进行超时，避免导致所有的信息都没有返回给前端；
> [Optimize]Topic-Partitions增加主动超时功能

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/connect/ConnectCluster.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/po/connect/ConnectClusterPO.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/cluster/impl/ConnectClusterServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/connector/impl/ConnectorServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/plugin/impl/PluginServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/worker/impl/WorkerConnectorServiceImpl.java
- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/kafka/metadata/SyncConnectClusterAndWorkerTask.java
问题：
clusterUrl动态更新可能会获取到错误的地址，导致请求connect集群相关信息失败；
解决：
去除动态更新，仅支持用户输入；
遗留：
前端需要支持用户输入；
> [Optimize]去除对Connect集群的clusterUrl的动态更新

- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/connect/connector/impl/ConnectorManagerImpl.java
- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/connect/mm2/impl/MirrorMakerManagerImpl.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/dto/connect/connector/ConnectorCreateDTO.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/dto/connect/mm2/MirrorMakerCreateDTO.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/vo/cluster/mm2/MirrorMakerBaseStateVO.java
- km-rest/src/main/java/com/xiaojukeji/know/streaming/km/rest/api/v3/connect/KafkaConnectorController.java
1、保持和原生一致；
2、当前是兼容状态，可同时支持configs和config；
> [Optimize]Connector增改接口的configs字段名调整为config

- docs/install_guide/版本升级手册.md
- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/group/impl/GroupManagerImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/group/OpGroupService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/group/impl/OpGroupServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/version/fe/FrontEndControlVersionItems.java
- km-persistence/src/main/resources/sql/dml-logi.sql
1、修复版本控制错误的问题；
2、增加相关权限点；
PS：仅后端代码，前端待补充。
> [Feature]新增Group及GroupOffset删除功能Part2

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/metrics/connect/ConnectClusterMetrics.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/metrics/connect/ConnectWorkerMetrics.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/metrics/connect/ConnectorMetrics.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/metrics/connect/ConnectorTaskMetrics.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/enums/connect/ConnectStatusEnum.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/cluster/impl/ConnectClusterMetricServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/connector/impl/ConnectorMetricServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/mm2/impl/MirrorMakerMetricServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/version/BaseConnectMetricService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/version/BaseConnectVersionControlService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/version/metrics/connect/ConnectorMetricVersionItems.java
- km-extends/km-monitor/src/main/java/com/xiaojukeji/know/streaming/km/monitor/common/MonitorSinkTagEnum.java
- km-extends/km-monitor/src/main/java/com/xiaojukeji/know/streaming/km/monitor/component/AbstractMonitorSinkService.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/connect/cluster/ConnectClusterMetricESDAO.java
1、增加Connector运行状态指标；
2、将Connector指标上报普罗米修斯；
3、调整代码继承关系；
> [Optimize]增加Connector运行状态指标

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/group/impl/GroupServiceImpl.java
- km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/kafka/KafkaAdminClient.java
1、增加AdminClient的ClientID；
2、关闭时，增加超时时间；
3、增加关闭错误的日志；
> [Optimize]增加AdminClient观测信息

- km-extends/km-account/src/main/java/com/xiaojukeji/know/streaming/km/account/login/ldap/LdapLoginServiceImpl.java
configure LDAP authentication and set auth-user-registration: false, result in NPE(Null Pointer Exception) #1116
fix NPE issue #1116
configure LDAP authentication and set auth-user-registration: false
> [Bugfix] 修复配置ldap登录，并设置auth-user-registration: false的空指针异常

- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/connect/connector/impl/ConnectorManagerImpl.java
- km-biz/src/main/java/com/xiaojukeji/know/streaming/km/biz/connect/mm2/impl/MirrorMakerManagerImpl.java
- km-collector/src/main/java/com/xiaojukeji/know/streaming/km/collector/metric/connect/ConnectConnectorMetricCollector.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/entity/meta/KafkaMetaService.java
- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/converter/ConnectConverter.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/connector/ConnectorService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/connector/OpConnectorService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/connector/impl/ConnectorServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/connector/impl/OpConnectorServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/group/impl/GroupServiceImpl.java
- km-rest/src/main/java/com/xiaojukeji/know/streaming/km/rest/api/v3/connect/KafkaConnectorController.java
- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/connect/metadata/SyncConnectorTask.java
1、引入KafkaMetaService；
2、将Connector的更新按照KafkaMetaService进行更新；
3、简化Connect-MirrorMaker的关联逻辑；
4、GroupService创建的AdminClient中的ClientID增加时间戳，减少Mbean冲突；
> [Optimize]统一DB元信息更新格式-Part1

- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/acl/KafkaAclService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/acl/OpKafkaAclService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/acl/impl/KafkaAclServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/acl/impl/OpKafkaAclServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/connector/ConnectorService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/meta/MetaDataService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/zookeeper/ZookeeperService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/zookeeper/impl/ZookeeperServiceImpl.java
- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/kafka/metadata/SyncKafkaAclTask.java
- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/kafka/metadata/SyncZookeeperTask.java
1、KafkaMetaService修改为MetaService并移动到Core层；
2、修改ZK、KafkaACL的格式；
> [Optimize]统一DB元信息更新格式-Part2

- km-common/src/main/java/com/xiaojukeji/know/streaming/km/common/bean/event/cluster/connect/ClusterPhyDeletedEvent.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/cluster/impl/ClusterPhyServiceImpl.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/cluster/ConnectClusterService.java
- km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/connect/cluster/impl/ConnectClusterServiceImpl.java
- km-task/src/main/java/com/xiaojukeji/know/streaming/km/task/service/listener/TaskClusterDeletedListener.java
原因：
首先，删除Kafka集群后，没有将DB中的Connect集群进行删除。随后，进行Connect集群指标采集时，由于所在的Kafka集群已经不存在了。最终，导致NPE；
解决：
发布一个Kafka集群删除事件，触发MetaDataService子类，将其在DB中的数据进行删除。
遗留：
当前MetaDataService仅在部分元信息同步类中实现，导致当前DB中的脏数据清理不彻底，后续等MetaDataService在所有元信息同步类中实现后，便可彻底清理数据。
PS：当前修复已保证NPE问题不会再出现。
> [Bugfix]修复删除Kafka集群后，Connect集群任务出现NPE问题

- km-console/packages/layout-clusters-fe/src/pages/Connect/AddConnector.tsx
- km-console/packages/layout-clusters-fe/src/pages/Connect/AddConnectorUseJSON.tsx
> [Bugfix]Connect-JSON模式下的JSON格式和官方API的格式不一致(#1048)

- km-console/packages/layout-clusters-fe/src/pages/CommonConfig.tsx
- km-console/packages/layout-clusters-fe/src/pages/SecurityACLs/index.tsx
- km-console/packages/layout-clusters-fe/src/pages/SecurityUsers/index.tsx
> [Optimize]security下的users、acls接入进权限管理(#1089)

- km-console/packages/layout-clusters-fe/src/app.tsx
- km-console/packages/layout-clusters-fe/src/pages/CommonConfig.tsx
修复未勾选系统管理查看权限，但是依然可以查看系统管理的问题
修复未勾选系统管理查看权限，但是依然可以查看系统管理的问题
> [Bugfix]修复未勾选系统管理查看权限，但是依然可以查看系统管理的问题

- km-console/packages/layout-clusters-fe/src/pages/TestingConsumer/Consume.tsx
- km-console/packages/layout-clusters-fe/src/pages/TestingConsumer/config.tsx
- km-enterprise/km-testing/src/main/java/com/xiaojukeji/know/streaming/km/testing/biz/impl/KafkaClientTestManagerImpl.java
- km-enterprise/km-testing/src/main/java/com/xiaojukeji/know/streaming/km/testing/common/bean/dto/KafkaConsumerFilterDTO.java
- km-enterprise/km-testing/src/main/java/com/xiaojukeji/know/streaming/km/testing/common/enums/KafkaConsumerFilterEnum.java
close #1155
Consume just filter key or value, not both.
消费消息支持单独过滤key或者value。
> [Feature] #1155 Consume just filter key or value, not both. 消费消息支持单独过滤key或者value.
